### DISCUSSION TITLE
not authorized on testdatabase to execute command { drop: "system.views"

### DISCUSSION THREAD

**Discussion by masterbater** [jenssegers/laravel-mongodb#3276] [Q&A]
In mongodb atlas I can drop views but when doing it in eloquent I cant seem to remove views

```yaml
  mongodb:
        image: 'mongodb/mongodb-atlas-local:latest'
        environment:
            - 'MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}'
            - 'MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}'
        volumes:
            - 'sail-mongodb:/data/db'
            - 'config:/data/configdb'
        ports:
            - '${FORWARD_MONGODB_PORT:-27017}:27017'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mongosh
                - 'mongodb://localhost:27017/admin'
                - '--eval=db.runCommand({ping:1})'
            retries: 3
            timeout: 5s

```

I can drop views by this command     DB::getCollection('users_combined')->drop();
, but when doing test it causes issues when using DatabaseMigrations  or any testing traits.

```
  not authorized on testdatabase to execute command { drop: "system.views", $db: "testdatabase ", lsid: { id: UUID("7a674d4e-653c-44d1-854d-e153c09bf08e") }, $clusterTime: { clusterTime: Timestamp(1739414070, 1), signature: { hash: BinData(0, AA71FCB85DAE6D1A4D6CCAB6F95A35AF868C36C2), keyId: 7469736761048956935 } } }

  at vendor/mongodb/mongodb/src/Operation/DropCollection.php:109
    105▕             throw UnsupportedException::writeConcernNotSupportedInTransaction();
    106▕         }
    107▕ 
    108▕         try {
  ➜ 109▕             $cursor = $server->executeWriteCommand($this->databaseName, $this->createCommand(), $this->createOptions());
    110▕         } catch (CommandException $e) {
    111▕             /* The server may return an error if the collection does not exist.
    112▕              * Check for an error code and return the command reply instead of
    113▕              * throwing. */

      +36 vendor frames 
  37  tests/TestCase.php:11
```
parent::setUp(); is line 11
